#!/bin/bash

# Disable firewall
systemctl disable firewalld
systemctl stop firewalld

# Add the Kubernetes repository
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

# Update packages
yum update -y

# Install Docker
yum install -y docker

# Start and enable Docker
systemctl start docker
systemctl enable docker

# Install kubeadm, kubelet, and kubectl
yum install -y kubeadm kubelet kubectl

# Enable and start kubelet
systemctl start kubelet
systemctl enable kubelet

# Initialize the cluster using kubeadm
kubeadm init --ignore-preflight-errors=CRI

# Configure kubectl
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

# Deploy the pod network
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
